package port;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.function.Function;

public interface IHandlerFactory<E> {
    IExpressionFactory<E> expressionFactory();

    Function<E, Map<Integer, Integer>> arithmeticDepthHistogramBuilder();
    Function<E, List<String>> arithmeticOperatorLabelCollector();
    Function<E, Map<Integer, Integer>> arityHistogramBuilder();
    Function<E, List<Integer>> binaryNodeDepthSequenceBuilder();
    Function<E, Integer> binaryOperatorCounter();
    Function<E, Map<Integer, Integer>> binaryOperatorDepthHistogramBuilder();
    Function<E, List<String>> binaryOperatorLabelCollector();
    Function<E, Integer> booleanOperatorCounter();
    Function<E, Map<Integer, Integer>> booleanOperatorDepthHistogramBuilder();
    Function<E, List<String>> booleanOperatorLabelCollector();
    Function<E, Map<Integer, Integer>> branchingFactorHistogramBuilder();
    Function<E, String> breadthFirstLabelPrinter();
    Function<E, String> compactInfixPrinter();
    Function<E, Map<Integer, Integer>> comparisonDepthHistogramBuilder();
    Function<E, List<String>> comparisonLabelCollector();
    Function<E, Integer> comparisonOperatorCounter();
    Function<E, List<String>> conditionalBranchLabelCollector();
    Function<E, Integer> conditionalCounter();
    Function<E, List<Integer>> conditionalDepthSequenceBuilder();
    Function<E, List<String>> conditionalPathCollector();
    Function<E, Boolean> constantExpressionChecker();
    Function<E, E> constantFolder();
    Function<E, String> csvNodeExporter();
    Function<E, String> deepestNodePathFinder();
    Function<E, String> depthAnnotatedPreorderPrinter();
    Function<E, Integer> depthCalculator();
    Function<E, Set<String>> distinctLeafLabelCollector();
    Function<E, String> dotGraphExporter();
    Function<E, Integer> evaluationComplexityScorer();
    Function<E, List<String>> evaluationOrderListBuilder();
    Function<E, String> executionPlanBuilder();
    Function<E, String> expressionFingerprintReporter();
    Function<E, String> expressionSummaryReporter();
    Function<E, List<String>> functionArgumentRootCollector();
    Function<E, List<Integer>> functionArityCollector();
    Function<E, List<Integer>> functionAritySequenceBuilder();
    Function<E, Integer> functionCallCounter();
    Function<E, List<Integer>> functionCallDepthSequenceBuilder();
    Function<E, List<String>> functionCallPathCollector();
    Function<E, List<String>> functionCallSignatureCollector();
    Function<E, Set<String>> functionNameCollector();
    Function<E, String> htmlExpressionExporter();
    Consumer<E> indentedTracePrinter();
    Function<E, Integer> integerEvaluator();
    Function<E, Integer> integerEvaluator(Map<String, Integer> variables, Map<String, Function<List<Integer>, Integer>> functions);
    Function<E, String> javaLikeExpressionEmitter();
    Function<E, String> jsonExporter();
    Function<E, Integer> leafCounter();
    Function<E, Map<Integer, Integer>> leafDepthHistogramBuilder();
    Function<E, List<Integer>> leafDepthSequenceBuilder();
    Function<E, List<String>> leafLabelSequenceBuilder();
    Function<E, List<String>> leafPathCollector();
    Function<E, Map<Integer, List<String>>> levelGroupedLabelCollector();
    Function<E, Map<Integer, Integer>> levelWidthHistogramBuilder();
    Function<E, List<String>> literalCollector();
    Function<E, Map<Integer, Integer>> literalDepthHistogramBuilder();
    Function<E, List<Integer>> literalDepthSequenceBuilder();
    Function<E, Map<String, Integer>> literalFrequencyBuilder();
    Function<E, Map<Integer, Integer>> literalLengthHistogramBuilder();
    Function<E, Map<String, List<String>>> literalPathCollector();
    Function<E, Integer> literalValueExtractor();
    Function<E, String> longestLiteralFinder();
    Function<E, String> longestVariableNameFinder();
    Function<E, String> markdownOutlineExporter();
    Function<E, Integer> maxFunctionArityFinder();
    Function<E, Integer> maximumBranchingFactorFinder();
    Function<E, String> mermaidFlowchartExporter();
    Function<E, String> mermaidMindmapExporter();
    Function<E, Integer> nodeCounter();
    Function<E, Map<String, Integer>> nodeHistogramBuilder();
    Function<E, List<String>> nodePathCollector();
    Function<E, Set<String>> nodeTypeCollector();
    Function<E, List<String>> nonLeafDepthSequenceBuilder();
    Function<E, Map<String, Integer>> operatorHistogramBuilder();
    Function<E, List<String>> operatorSequenceCollector();
    Function<E, String> parenthesizedInfixPrinter();
    Function<E, String> pathAnnotatedOutlineExporter();
    Function<E, String> postOrderLabelPrinter();
    Function<E, String> prefixNotationPrinter();
    Function<E, String> reversePolishPrinter();
    Function<E, String> rootToLeafTracePrinter();
    Function<E, String> sExpressionExporter();
    Function<E, String> shallowestLeafPathFinder();
    Function<E, Boolean> sideEffectFreeChecker();
    Function<E, Integer> structuralHashBuilder();
    Function<E, String> structuralSignatureBuilder();
    Function<E, List<String>> subexpressionListingBuilder();
    Function<E, String> treeDiagramPrinter();
    Function<E, String> tsvNodeExporter();
    Function<E, List<Integer>> unaryNodeDepthSequenceBuilder();
    Function<E, Integer> unaryOperatorCounter();
    Function<E, Map<Integer, Integer>> unaryOperatorDepthHistogramBuilder();
    Function<E, List<String>> unaryOperatorLabelCollector();
    Function<E, Set<String>> variableCollector();
    Function<E, Map<Integer, Integer>> variableDepthHistogramBuilder();
    Function<E, List<Integer>> variableDepthSequenceBuilder();
    Function<E, Map<Integer, Integer>> variableNameLengthHistogramBuilder();
    Function<E, Map<String, List<String>>> variablePathCollector();
    Function<E, E> variableReferenceExtractor();
    Function<E, Map<String, Integer>> variableUsageCounter();
    Function<E, String> xmlExporter();
    Function<E, String> yamlExpressionExporter();
    Function<E, Boolean> zeroDivisionRiskDetector();
}