package port;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

import lib.expression.Visitor;

public interface IVisitorFactory<E> {
    IExpressionFactory<E> expressionFactory();

    Visitor<Map<Integer, Integer>> arithmeticDepthHistogramBuilder();
    Visitor<List<String>> arithmeticOperatorLabelCollector();
    Visitor<Map<Integer, Integer>> arityHistogramBuilder();
    Visitor<List<Integer>> binaryNodeDepthSequenceBuilder();
    Visitor<Integer> binaryOperatorCounter();
    Visitor<Map<Integer, Integer>> binaryOperatorDepthHistogramBuilder();
    Visitor<List<String>> binaryOperatorLabelCollector();
    Visitor<Integer> booleanOperatorCounter();
    Visitor<Map<Integer, Integer>> booleanOperatorDepthHistogramBuilder();
    Visitor<List<String>> booleanOperatorLabelCollector();
    Visitor<Map<Integer, Integer>> branchingFactorHistogramBuilder();
    Visitor<String> breadthFirstLabelPrinter();
    Visitor<String> compactInfixPrinter();
    Visitor<Map<Integer, Integer>> comparisonDepthHistogramBuilder();
    Visitor<List<String>> comparisonLabelCollector();
    Visitor<Integer> comparisonOperatorCounter();
    Visitor<List<String>> conditionalBranchLabelCollector();
    Visitor<Integer> conditionalCounter();
    Visitor<List<Integer>> conditionalDepthSequenceBuilder();
    Visitor<List<String>> conditionalPathCollector();
    Visitor<Boolean> constantExpressionChecker();
    Visitor<E> constantFolder();
    Visitor<String> csvNodeExporter();
    Visitor<String> deepestNodePathFinder();
    Visitor<String> depthAnnotatedPreorderPrinter();
    Visitor<Integer> depthCalculator();
    Visitor<Set<String>> distinctLeafLabelCollector();
    Visitor<String> dotGraphExporter();
    Visitor<Integer> evaluationComplexityScorer();
    Visitor<List<String>> evaluationOrderListBuilder();
    Visitor<String> executionPlanBuilder();
    Visitor<String> expressionFingerprintReporter();
    Visitor<String> expressionSummaryReporter();
    Visitor<List<String>> functionArgumentRootCollector();
    Visitor<List<Integer>> functionArityCollector();
    Visitor<List<Integer>> functionAritySequenceBuilder();
    Visitor<Integer> functionCallCounter();
    Visitor<List<Integer>> functionCallDepthSequenceBuilder();
    Visitor<List<String>> functionCallPathCollector();
    Visitor<List<String>> functionCallSignatureCollector();
    Visitor<Set<String>> functionNameCollector();
    Visitor<String> htmlExpressionExporter();
    Visitor<Void> indentedTracePrinter();
    Visitor<Integer> integerEvaluator();
    Visitor<Integer> integerEvaluator(Map<String, Integer> variables, Map<String, Function<List<Integer>, Integer>> functions);
    Visitor<String> javaLikeExpressionEmitter();
    Visitor<String> jsonExporter();
    Visitor<Integer> leafCounter();
    Visitor<Map<Integer, Integer>> leafDepthHistogramBuilder();
    Visitor<List<Integer>> leafDepthSequenceBuilder();
    Visitor<List<String>> leafLabelSequenceBuilder();
    Visitor<List<String>> leafPathCollector();
    Visitor<Map<Integer, List<String>>> levelGroupedLabelCollector();
    Visitor<Map<Integer, Integer>> levelWidthHistogramBuilder();
    Visitor<List<String>> literalCollector();
    Visitor<Map<Integer, Integer>> literalDepthHistogramBuilder();
    Visitor<List<Integer>> literalDepthSequenceBuilder();
    Visitor<Map<String, Integer>> literalFrequencyBuilder();
    Visitor<Map<Integer, Integer>> literalLengthHistogramBuilder();
    Visitor<Map<String, List<String>>> literalPathCollector();
    Visitor<Integer> literalValueExtractor();
    Visitor<String> longestLiteralFinder();
    Visitor<String> longestVariableNameFinder();
    Visitor<String> markdownOutlineExporter();
    Visitor<Integer> maxFunctionArityFinder();
    Visitor<Integer> maximumBranchingFactorFinder();
    Visitor<String> mermaidFlowchartExporter();
    Visitor<String> mermaidMindmapExporter();
    Visitor<Integer> nodeCounter();
    Visitor<Map<String, Integer>> nodeHistogramBuilder();
    Visitor<List<String>> nodePathCollector();
    Visitor<Set<String>> nodeTypeCollector();
    Visitor<List<String>> nonLeafDepthSequenceBuilder();
    Visitor<Map<String, Integer>> operatorHistogramBuilder();
    Visitor<List<String>> operatorSequenceCollector();
    Visitor<String> parenthesizedInfixPrinter();
    Visitor<String> pathAnnotatedOutlineExporter();
    Visitor<String> postOrderLabelPrinter();
    Visitor<String> prefixNotationPrinter();
    Visitor<String> reversePolishPrinter();
    Visitor<String> rootToLeafTracePrinter();
    Visitor<String> sExpressionExporter();
    Visitor<String> shallowestLeafPathFinder();
    Visitor<Boolean> sideEffectFreeChecker();
    Visitor<Integer> structuralHashBuilder();
    Visitor<String> structuralSignatureBuilder();
    Visitor<List<String>> subexpressionListingBuilder();
    Visitor<String> treeDiagramPrinter();
    Visitor<String> tsvNodeExporter();
    Visitor<List<Integer>> unaryNodeDepthSequenceBuilder();
    Visitor<Integer> unaryOperatorCounter();
    Visitor<Map<Integer, Integer>> unaryOperatorDepthHistogramBuilder();
    Visitor<List<String>> unaryOperatorLabelCollector();
    Visitor<Set<String>> variableCollector();
    Visitor<Map<Integer, Integer>> variableDepthHistogramBuilder();
    Visitor<List<Integer>> variableDepthSequenceBuilder();
    Visitor<Map<Integer, Integer>> variableNameLengthHistogramBuilder();
    Visitor<Map<String, List<String>>> variablePathCollector();
    Visitor<E> variableReferenceExtractor();
    Visitor<Map<String, Integer>> variableUsageCounter();
    Visitor<String> xmlExporter();
    Visitor<String> yamlExpressionExporter();
    Visitor<Boolean> zeroDivisionRiskDetector();
}